### ISSUE TITLE
Output to a pulseaudio device an OBS source by adding filter

### ISSUE THREAD

**Issue by ogmkp** [jbwong05/obs-pulseaudio-app-capture#1]
Hello and thank you for this project.

I'm looking for a way to output the sound from an OBS source to a pulseaudio sound card as a filter.
Would you know a solution?

Thank you.

**Comment by jbwong05** [comment]
I'm not too familiar with OBS filters, but from what I understand, they can receive raw audio, transform it, and then send it back to OBS for output. I'm not  sure if that would helpful for your use case. You may be able to solve your problem by using pulseaudio to attach the OBS monitor for your source to to the desired sound card

**Comment by ogmkp** [comment]
Yes, filters are associated with sources. I'm looking for a way to add a filter on a source (video, music) to output the sound to a device other (mirroring) than the device configured as monitoring in the OBS settings.

**Comment by WizardCM** [comment]
For reference, here's a plugin that provides this capability for Windows and macOS: https://github.com/exeldro/obs-audio-monitor

**Comment by ogmkp** [comment]
Yes @WizardCM 
The only thing missing with exeldro's obs-audio-monitor is that it is not pulseaudio compatible, already requested here by myself: 
https://github.com/exeldro/obs-audio-monitor/issues/4

**Comment by ogmkp** [comment]
As mentioned in the README, this plugin seems to be no longer in development. I'm closing this ticket.
